version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  copy:
    desc: Copy plugin.js to clipboard (for pasting into Thymer)
    cmds:
      - cat plugin.js | wl-copy
      - echo "plugin.js copied to clipboard"

  copy-json:
    desc: Copy plugin.json to clipboard
    cmds:
      - cat plugin.json | wl-copy
      - echo "plugin.json copied to clipboard"

  copy-all:
    desc: Copy both plugin.js and plugin.json (js first, then json)
    cmds:
      - cat plugin.js | wl-copy
      - echo "plugin.js copied - paste it, then press Enter to copy plugin.json"
      - read
      - cat plugin.json | wl-copy
      - echo "plugin.json copied to clipboard"

  test:
    desc: Create test markdown file and copy to clipboard
    cmds:
      - |
        cat <<'EOF' | wl-copy
        # Heading 1

        ## Heading 2 with **bold**

        Regular paragraph with **bold**, *italic*, and `code`.

        - Bullet one
        - Bullet with **formatting**

        1. First item
        2. Second item

        > Blockquote text

        - [ ] Unchecked task
        - [x] Checked task

        ```javascript
        function hello() {
            return "world";
        }
        ```

        Final paragraph.
        EOF
      - echo "Test markdown copied to clipboard"

  commit:
    desc: Git add, commit with message, and push
    cmds:
      - git add .
      - git commit -m "{{.CLI_ARGS}}"
      - git push

  status:
    desc: Show git status
    cmds:
      - git status

  log:
    desc: Show recent git log
    cmds:
      - git log --oneline -10

  # Server tasks
  build:
    desc: Build the tm server binary
    dir: server
    cmds:
      - go build -o tm .
      - echo "Built server/tm"

  install:
    desc: Install tm binary to ~/.local/bin
    deps: [build]
    cmds:
      - mkdir -p ~/.local/bin
      - cp server/tm ~/.local/bin/tm
      - chmod +x ~/.local/bin/tm
      - echo "Installed to ~/.local/bin/tm"
      - echo "Make sure ~/.local/bin is in your PATH"

  service:install:
    desc: Install systemd user service for tm server
    cmds:
      - mkdir -p ~/.config/systemd/user
      - mkdir -p ~/.local/share/thymer-paste/logs
      - |
        cat > ~/.config/systemd/user/thymer-paste.service << 'EOF'
        [Unit]
        Description=Thymer Paste Bridge Server
        After=network.target

        [Service]
        Type=simple
        ExecStart=%h/.local/bin/tm server
        Restart=on-failure
        RestartSec=5
        StandardOutput=append:%h/.local/share/thymer-paste/logs/server.log
        StandardError=append:%h/.local/share/thymer-paste/logs/server.log

        [Install]
        WantedBy=default.target
        EOF
      - systemctl --user daemon-reload
      - systemctl --user enable thymer-paste.service
      - echo "Service installed and enabled"
      - echo "Run 'task service:start' to start it"

  service:start:
    desc: Start the tm server service
    cmds:
      - systemctl --user start thymer-paste.service
      - echo "Service started"
      - systemctl --user status thymer-paste.service --no-pager

  service:stop:
    desc: Stop the tm server service
    cmds:
      - systemctl --user stop thymer-paste.service
      - echo "Service stopped"

  service:restart:
    desc: Restart the tm server service
    cmds:
      - systemctl --user restart thymer-paste.service
      - echo "Service restarted"

  service:status:
    desc: Show tm server service status
    cmds:
      - systemctl --user status thymer-paste.service --no-pager

  service:logs:
    desc: Show tm server logs
    cmds:
      - tail -f ~/.local/share/thymer-paste/logs/server.log

  service:uninstall:
    desc: Stop and remove the systemd service
    cmds:
      - systemctl --user stop thymer-paste.service || true
      - systemctl --user disable thymer-paste.service || true
      - rm -f ~/.config/systemd/user/thymer-paste.service
      - systemctl --user daemon-reload
      - echo "Service removed"
